# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0009_auto_20160217_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='filelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('la', models.CharField(max_length=20)),
                ('lo', models.CharField(max_length=20)),
                ('geoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.geo')),
            ],
        ),
        migrations.CreateModel(
            name='namepw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='filelist',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.namepw'),
        ),
    ]
