# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20160217_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geoid',
            field=models.CharField(max_length=20),
        ),
    ]
