# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20160219_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filelist',
        ),
        migrations.DeleteModel(
            name='geo',
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
