# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20160222_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='filelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
